# SPDX-FileCopyrightText: 2021 Avinal Kumar <avinal.xlvii@gmail.com>
# SPDX-License-Identifier: GPL-2.0 AND LGPL-2.

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    continue-on-error: ${{ matrix.config.experimental }}
    services:
      postgres:
        image: postgres:13
        env: 
          POSTGRES_DB: fossology
          POSTGRES_USER: fossy
          POSTGRES_PASSWORD: fossy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu 20.04 GCC 9",
            os: ubuntu-20.04,
            build_type: "Debug", 
            cc: "gcc-9", 
            cxx: "g++-9",
            experimental: false
          }
        - {
            name: "Ubuntu 20.04 GCC 8",
            os: ubuntu-20.04,
            build_type: "Debug", 
            cc: "gcc-8", 
            cxx: "g++-8",
            experimental: false
          }
        # FIXME: GHA Virual Environment doesn't have a version of glib-cli required by fossology
        - {
            name: "Ubuntu 18.04 GCC 7",
            os: ubuntu-18.04,
            build_type: "Debug", 
            cc: "gcc-7", 
            cxx: "g++-7",
            experimental: true
          }
        # clang is experimental for now
        - {
            name: "Ubuntu 20.04 CLANG",
            os: ubuntu-20.04,
            build_type: "Debug", 
            cc: "clang", 
            cxx: "clang++",
            experimental: true
          }
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-system-dev libboost-filesystem-dev libcppunit-dev libcunit1-dev libdbd-sqlite3-perl libjsoncpp-dev libjson-c-dev liblocal-lib-perl   libspreadsheet-writeexcel-perl libtext-template-perl libgcrypt20-dev
          sudo ./utils/fo-installdeps --everything
          export PATH="/usr/lib/ccache/:$PATH"
          export COMPOSER_HOME="$HOME/.composer/"

      - name: Install additional Dependencies
        if: ${{ matrix.config.cc == 'gcc-8' }}
        run: sudo apt install -y gcc-8 g++-8

      - name: Configure and Generate CMake Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -GNinja -DTESTING=ON ..
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}

      - name: Build Project
        run: cmake --build build --config ${{ matrix.config.build_type }}

      - name: Prepare and Run Tests
        run: |
          sudo ./utils/prepare-test
          cd build
          ctest --output-on-failure
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
