name: PHPUnit Tests

on:
  push:
    branches: [ phpunit-tests ]
    pull_request: [ phpunit-tests ]

jobs:
  phpunit-test:
    strategy:
      matrix:
        include:
          # - toolset: php7.0
          #   phpstd: "7.0"
          #   os: ubuntu-16.04
          # - toolset: php7.1
          #   phpstd: "7.1"
          #   os: ubuntu-18.04
          # - toolset: php7.2
          #   phpstd: "7.2"
          #   os: ubuntu-18.04
          - toolset: php7.2
            phpstd: "7.2"
            os: ubuntu-20.04
            pgsql: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt-get install -y libmxml-dev curl libxml2-dev libcunit1-dev libicu-dev \
            build-essential libtext-template-perl subversion rpm librpm-dev \
            libmagic-dev libglib2.0 libboost-regex-dev \
            libboost-program-options-dev libpq-dev composer patch devscripts \
            libdistro-info-perl php-mbstring php7.2-cli php7.2-xml php7.2-zip
          export PATH="/usr/lib/ccache/:$PATH"
          export COMPOSER_HOME="$HOME/.composer/"
          sudo update-alternatives --set php "/usr/bin/php${{ matrix.phpstd }}"
      - name: Install Composer Packages
        run: composer update --ignore-platform-reqs --with-dependencies --prefer-dist --working-dir=src phpunit/phpunit

      - name: Set up PostgreSQL
        if: matrix.pgsql
        run: |
          sudo apt install -y postgresql-10 postgresql-client-10
          export PGPORT="5432"
          sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
          sudo service postgresql restart
      
      - name: Prepare Tests
        run: |
          ./utils/prepare-test -afty

      - name: Run Tests
        run: |
          set -o pipefail
          make build-lib VERSIONFILE build-cli
          echo "here"
          phpdbg -qrr src/vendor/bin/phpunit -csrc/phpunit.xml --testsuite="Fossology PhpUnit Test Suite" --colors=always | grep -v 'script>\|c.log'
      - name: After test
        run: php src/vendor/bin/php-coveralls -vv -o coveralls.json -x clover.xml

        # php${{ matrix.phpstd }}-cli \
        #     php${{ matrix.phpstd }}-pgsql \
        #     php${{ matrix.phpstd }}-zip \
        #     php${{ matrix.phpstd }}-xml \
        #     php-mbstring \
        #     libmxml-dev curl libxml2-dev libcunit1-dev libicu-dev \
        #     build-essential libtext-template-perl subversion rpm librpm-dev \
        #     libmagic-dev libglib2.0 libboost-regex-dev \
        #     libboost-program-options-dev libpq-dev composer patch devscripts \
        #     libdistro-info-perl