#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# SPDX-FileCopyrightText: 2021 Avinal Kumar <avinal.xlvii@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

export COMPOSER_HOME=/dev/null
export COMPOSER_ALLOW_SUPERUSER=1
composer install --no-plugins --no-scripts --no-dev

if ! patch --reverse --silent --force --dry-run vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/RdfXml.php RdfXml.php.patch > /dev/null
then
	echo "  - Applying easyrdf patch"
	if patch --silent --force vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/RdfXml.php RdfXml.php.patch
	then
		echo "  - Patched easyrdf successfully"
	fi
else
	echo "  - Already patched"
fi
